column_width = 80
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"

collapse_simple_statement = false
align_arguments = false
align_parameter = false
indent_expression = "Auto"

